services:
  - type: web
    name: komfort-hr-system
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: JWT_SECRET
        generateValue: true
